spring.application.name=restaurant

# datasource information
spring.datasource.url=**DB URL**
spring.datasource.username=**DB USERNAME**
spring.datasource.password=**DB PASSWORD**
spring.datasource.driver-class-name=** DRIVER **

# hibernate create/update tables in database
spring.jpa.hibernate.ddl-auto=update
